### ISSUE TITLE
Orb of Zot is autopicked

### ISSUE THREAD

**Issue by dominiquelee** [magus/dcss#10]
The default behavior is to autopick the 15 runes of Zot but not the Orb itself.

version: 1.9.6

**Comment by magus** [comment]
Thank you! This change fixes that issue, it'll be included in the next release

<img width="489" alt="Screen Shot 2021-04-14 at 5 02 42 PM" src="https://user-images.githubusercontent.com/290084/114795766-38ba4300-9d44-11eb-850a-e826f78fc056.png">
