### ISSUE TITLE
Enhancer staff issue.

### ISSUE THREAD

**Issue by mkell82** [magus/dcss#14]
I've seen it on all characters so far.   Here in this example I have found a staff of fire and a staff of conjuration on d1.  Maybe because I have no staff skill?

![image](https://user-images.githubusercontent.com/82546727/114787514-f4cc3b80-9d4d-11eb-8c8f-30f41b5fc39c.png)
![image](https://user-images.githubusercontent.com/82546727/114787658-26dd9d80-9d4e-11eb-887a-48e8481e40d0.png)

**Comment by magus** [comment]
Thanks, I was able to reproduce and this will be fixed in the next version
