### ISSUE TITLE
How do you disable boring prompts from needing more?

### ISSUE THREAD

**Issue by PointMeAtTheDawn** [magus/dcss#16]
Default behavior has dogs sniffing prompting 'more' behavior for me, when it looks like it's meant to be marked as boring / boring aren't meant to prompt this.

**Comment by magus** [comment]
Hm I wasn't able to reproduce this with other boring prompts, do you have a screenshot for the specific log line? I do see we have this set to boring

```lua
msc += $boring:Grum sniffs the air and quickly glances around
```
> https://github.com/magus/dcss/blob/326a05b5268705166e628aa7318608d7d28a7957/compile-rc/parts/Messages.rc#L1235

```lua
msc += $boring:(gazes forward|pauses|quivers|skips|sputters|stops to sniff|summons a swarm of flies)
```
> https://github.com/magus/dcss/blob/326a05b5268705166e628aa7318608d7d28a7957/compile-rc/parts/Messages.rc#L1356
